use super::adaptivity::Adaptivity::*;
use super::descriptor::Descriptor;
use super::identifier::Identifier::*;
use super::input_requirement::InputRequirement::*;
use super::output_descriptor::OutputDescriptor;
use super::outputs::shape::Shape::*;
use super::pane::Pane::*;
use super::role::Role::*;
use super::volume_usage::VolumeUsage::*;

/// Static registry of taxonomic descriptors for all implemented indicators.
/// Output Kind values are 1-based (matching Go's iota+1 per-indicator output enums).
pub static DESCRIPTORS: &[Descriptor] = &[
    Descriptor {
        identifier: SimpleMovingAverage,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: WeightedMovingAverage,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: TriangularMovingAverage,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: ExponentialMovingAverage,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: DoubleExponentialMovingAverage,
        family: "Patrick Mulloy",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: TripleExponentialMovingAverage,
        family: "Patrick Mulloy",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: T2ExponentialMovingAverage,
        family: "Tim Tillson",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: T3ExponentialMovingAverage,
        family: "Tim Tillson",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: KaufmanAdaptiveMovingAverage,
        family: "Perry Kaufman",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: JurikMovingAverage,
        family: "Mark Jurik",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: JurikRelativeTrendStrengthIndex,
        family: "Mark Jurik",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: JurikCompositeFractalBehaviorIndex,
        family: "Mark Jurik",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: JurikZeroLagVelocity,
        family: "Mark Jurik",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: MesaAdaptiveMovingAverage,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 3,
                shape: Band,
                role: Envelope,
                pane: Price,
            },
        ],
    },
    Descriptor {
        identifier: FractalAdaptiveMovingAverage,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: FractalDimension,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: DominantCycle,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: CyclePeriod,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: CyclePeriod,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: CyclePhase,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: Momentum,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: RateOfChange,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: RateOfChangePercent,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: RelativeStrengthIndex,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: BoundedOscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: ChandeMomentumOscillator,
        family: "Tushar Chande",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: BoundedOscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: BollingerBands,
        family: "John Bollinger",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Envelope,
                pane: Price,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Envelope,
                pane: Price,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
            OutputDescriptor {
                kind: 5,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 6,
                shape: Band,
                role: Envelope,
                pane: Price,
            },
        ],
    },
    Descriptor {
        identifier: Variance,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Volatility,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: StandardDeviation,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Volatility,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: GoertzelSpectrum,
        family: "Custom",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Heatmap,
            role: Spectrum,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: CenterOfGravityOscillator,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Signal,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: CyberCycle,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Signal,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: InstantaneousTrendLine,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Signal,
                pane: Price,
            },
        ],
    },
    Descriptor {
        identifier: SuperSmoother,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: ZeroLagExponentialMovingAverage,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: ZeroLagErrorCorrectingExponentialMovingAverage,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: RoofingFilter,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: TrueRange,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Volatility,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: AverageTrueRange,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Volatility,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: NormalizedAverageTrueRange,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Volatility,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: DirectionalMovementMinus,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Directional,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: DirectionalMovementPlus,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Directional,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: DirectionalIndicatorMinus,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: DirectionalIndicatorPlus,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: DirectionalMovementIndex,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 5,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 6,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
            OutputDescriptor {
                kind: 7,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: AverageDirectionalMovementIndex,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 5,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 6,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 7,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
            OutputDescriptor {
                kind: 8,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: AverageDirectionalMovementIndexRating,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 5,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 6,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 7,
                shape: Scalar,
                role: Directional,
                pane: Own,
            },
            OutputDescriptor {
                kind: 8,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
            OutputDescriptor {
                kind: 9,
                shape: Scalar,
                role: Volatility,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: WilliamsPercentR,
        family: "Larry Williams",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: BoundedOscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: PercentagePriceOscillator,
        family: "Gerald Appel",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: AbsolutePriceOscillator,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: CommodityChannelIndex,
        family: "Donald Lambert",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: BoundedOscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: MoneyFlowIndex,
        family: "Gene Quong",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: AggregateBarVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: BoundedOscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: OnBalanceVolume,
        family: "Joseph Granville",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: AggregateBarVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: VolumeFlow,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: BalanceOfPower,
        family: "Igor Livshin",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: BoundedOscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: RateOfChangeRatio,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: PearsonsCorrelationCoefficient,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Correlation,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: LinearRegression,
        family: "Common",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 5,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: UltimateOscillator,
        family: "Larry Williams",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: BoundedOscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: StochasticRelativeStrengthIndex,
        family: "Tushar Chande",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Signal,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: Stochastic,
        family: "George Lane",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Signal,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: Aroon,
        family: "Tushar Chande",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: AdvanceDecline,
        family: "Marc Chaikin",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: AggregateBarVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: VolumeFlow,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: AdvanceDeclineOscillator,
        family: "Marc Chaikin",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: AggregateBarVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: VolumeFlow,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: ParabolicStopAndReverse,
        family: "Welles Wilder",
        adaptivity: Static,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Overlay,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: TripleExponentialMovingAverageOscillator,
        family: "Jack Hutson",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: BollingerBandsTrend,
        family: "John Bollinger",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: MovingAverageConvergenceDivergence,
        family: "Gerald Appel",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Signal,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Histogram,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: SineWave,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Signal,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Band,
                role: Envelope,
                pane: Own,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: CyclePeriod,
                pane: Own,
            },
            OutputDescriptor {
                kind: 5,
                shape: Scalar,
                role: CyclePhase,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: HilbertTransformerInstantaneousTrendLine,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: CyclePeriod,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: TrendCycleMode,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: RegimeFlag,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: RegimeFlag,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: RegimeFlag,
                pane: Own,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 5,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 6,
                shape: Scalar,
                role: Signal,
                pane: Own,
            },
            OutputDescriptor {
                kind: 7,
                shape: Scalar,
                role: CyclePeriod,
                pane: Own,
            },
            OutputDescriptor {
                kind: 8,
                shape: Scalar,
                role: CyclePhase,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: CoronaSpectrum,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Heatmap,
                role: Spectrum,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: CyclePeriod,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: CyclePeriod,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: CoronaSignalToNoiseRatio,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Heatmap,
                role: Spectrum,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: CoronaSwingPosition,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Heatmap,
                role: Spectrum,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: BoundedOscillator,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: CoronaTrendVigor,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Heatmap,
                role: Spectrum,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: AdaptiveTrendAndCycleFilter,
        family: "Vladimir Kravchuk",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 4,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 5,
                shape: Scalar,
                role: Smoother,
                pane: Price,
            },
            OutputDescriptor {
                kind: 6,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 7,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 8,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: MaximumEntropySpectrum,
        family: "Custom",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Heatmap,
            role: Spectrum,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: DiscreteFourierTransformSpectrum,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Heatmap,
            role: Spectrum,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: CombBandPassSpectrum,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Heatmap,
            role: Spectrum,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: AutoCorrelationIndicator,
        family: "John Ehlers",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Heatmap,
            role: Correlation,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: AutoCorrelationPeriodogram,
        family: "John Ehlers",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Heatmap,
            role: Spectrum,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: JurikDirectionalMovementIndex,
        family: "Mark Jurik",
        adaptivity: Adaptive,
        input_requirement: BarInput,
        volume_usage: NoVolume,
        outputs: &[
            OutputDescriptor {
                kind: 1,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 2,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
            OutputDescriptor {
                kind: 3,
                shape: Scalar,
                role: Oscillator,
                pane: Own,
            },
        ],
    },
    Descriptor {
        identifier: JurikTurningPointOscillator,
        family: "Mark Jurik",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: JurikWaveletSampler,
        family: "Mark Jurik",
        adaptivity: Static,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Smoother,
            pane: Price,
        }],
    },
    Descriptor {
        identifier: JurikAdaptiveRelativeTrendStrengthIndex,
        family: "Mark Jurik",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: JurikAdaptiveZeroLagVelocity,
        family: "Mark Jurik",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: JurikCommodityChannelIndex,
        family: "Mark Jurik",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
    Descriptor {
        identifier: JurikFractalAdaptiveZeroLagVelocity,
        family: "Mark Jurik",
        adaptivity: Adaptive,
        input_requirement: ScalarInput,
        volume_usage: NoVolume,
        outputs: &[OutputDescriptor {
            kind: 1,
            shape: Scalar,
            role: Oscillator,
            pane: Own,
        }],
    },
];
