/// Identifies an indicator by enumerating all implemented indicators.
/// Values are 0-based (unlike Go's iota+1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Identifier {
    SimpleMovingAverage = 0,
    WeightedMovingAverage = 1,
    TriangularMovingAverage = 2,
    ExponentialMovingAverage = 3,
    DoubleExponentialMovingAverage = 4,
    TripleExponentialMovingAverage = 5,
    T2ExponentialMovingAverage = 6,
    T3ExponentialMovingAverage = 7,
    KaufmanAdaptiveMovingAverage = 8,
    JurikMovingAverage = 9,
    MesaAdaptiveMovingAverage = 10,
    FractalAdaptiveMovingAverage = 11,
    DominantCycle = 12,
    Momentum = 13,
    RateOfChange = 14,
    RateOfChangePercent = 15,
    RelativeStrengthIndex = 16,
    ChandeMomentumOscillator = 17,
    BollingerBands = 18,
    Variance = 19,
    StandardDeviation = 20,
    GoertzelSpectrum = 21,
    CenterOfGravityOscillator = 22,
    CyberCycle = 23,
    InstantaneousTrendLine = 24,
    SuperSmoother = 25,
    ZeroLagExponentialMovingAverage = 26,
    ZeroLagErrorCorrectingExponentialMovingAverage = 27,
    RoofingFilter = 28,
    TrueRange = 29,
    AverageTrueRange = 30,
    NormalizedAverageTrueRange = 31,
    DirectionalMovementMinus = 32,
    DirectionalMovementPlus = 33,
    DirectionalIndicatorMinus = 34,
    DirectionalIndicatorPlus = 35,
    DirectionalMovementIndex = 36,
    AverageDirectionalMovementIndex = 37,
    AverageDirectionalMovementIndexRating = 38,
    WilliamsPercentR = 39,
    PercentagePriceOscillator = 40,
    AbsolutePriceOscillator = 41,
    CommodityChannelIndex = 42,
    MoneyFlowIndex = 43,
    OnBalanceVolume = 44,
    BalanceOfPower = 45,
    RateOfChangeRatio = 46,
    PearsonsCorrelationCoefficient = 47,
    LinearRegression = 48,
    UltimateOscillator = 49,
    StochasticRelativeStrengthIndex = 50,
    Stochastic = 51,
    Aroon = 52,
    AdvanceDecline = 53,
    AdvanceDeclineOscillator = 54,
    ParabolicStopAndReverse = 55,
    TripleExponentialMovingAverageOscillator = 56,
    BollingerBandsTrend = 57,
    MovingAverageConvergenceDivergence = 58,
    SineWave = 59,
    HilbertTransformerInstantaneousTrendLine = 60,
    TrendCycleMode = 61,
    CoronaSpectrum = 62,
    CoronaSignalToNoiseRatio = 63,
    CoronaSwingPosition = 64,
    CoronaTrendVigor = 65,
    AdaptiveTrendAndCycleFilter = 66,
    MaximumEntropySpectrum = 67,
    DiscreteFourierTransformSpectrum = 68,
    CombBandPassSpectrum = 69,
    AutoCorrelationIndicator = 70,
    AutoCorrelationPeriodogram = 71,
    JurikRelativeTrendStrengthIndex = 72,
    JurikCompositeFractalBehaviorIndex = 73,
    JurikZeroLagVelocity = 74,
    JurikDirectionalMovementIndex = 75,
    JurikCommodityChannelIndex = 76,
    JurikWaveletSampler = 77,
    JurikAdaptiveZeroLagVelocity = 78,
    JurikFractalAdaptiveZeroLagVelocity = 79,
    JurikAdaptiveRelativeTrendStrengthIndex = 80,
    JurikTurningPointOscillator = 81,
}

impl Identifier {
    /// Returns the camelCase string representation matching Go's String().
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::SimpleMovingAverage => "simpleMovingAverage",
            Self::WeightedMovingAverage => "weightedMovingAverage",
            Self::TriangularMovingAverage => "triangularMovingAverage",
            Self::ExponentialMovingAverage => "exponentialMovingAverage",
            Self::DoubleExponentialMovingAverage => "doubleExponentialMovingAverage",
            Self::TripleExponentialMovingAverage => "tripleExponentialMovingAverage",
            Self::T2ExponentialMovingAverage => "t2ExponentialMovingAverage",
            Self::T3ExponentialMovingAverage => "t3ExponentialMovingAverage",
            Self::KaufmanAdaptiveMovingAverage => "kaufmanAdaptiveMovingAverage",
            Self::JurikMovingAverage => "jurikMovingAverage",
            Self::MesaAdaptiveMovingAverage => "mesaAdaptiveMovingAverage",
            Self::FractalAdaptiveMovingAverage => "fractalAdaptiveMovingAverage",
            Self::DominantCycle => "dominantCycle",
            Self::Momentum => "momentum",
            Self::RateOfChange => "rateOfChange",
            Self::RateOfChangePercent => "rateOfChangePercent",
            Self::RelativeStrengthIndex => "relativeStrengthIndex",
            Self::ChandeMomentumOscillator => "chandeMomentumOscillator",
            Self::BollingerBands => "bollingerBands",
            Self::Variance => "variance",
            Self::StandardDeviation => "standardDeviation",
            Self::GoertzelSpectrum => "goertzelSpectrum",
            Self::CenterOfGravityOscillator => "centerOfGravityOscillator",
            Self::CyberCycle => "cyberCycle",
            Self::InstantaneousTrendLine => "instantaneousTrendLine",
            Self::SuperSmoother => "superSmoother",
            Self::ZeroLagExponentialMovingAverage => "zeroLagExponentialMovingAverage",
            Self::ZeroLagErrorCorrectingExponentialMovingAverage => {
                "zeroLagErrorCorrectingExponentialMovingAverage"
            }
            Self::RoofingFilter => "roofingFilter",
            Self::TrueRange => "trueRange",
            Self::AverageTrueRange => "averageTrueRange",
            Self::NormalizedAverageTrueRange => "normalizedAverageTrueRange",
            Self::DirectionalMovementMinus => "directionalMovementMinus",
            Self::DirectionalMovementPlus => "directionalMovementPlus",
            Self::DirectionalIndicatorMinus => "directionalIndicatorMinus",
            Self::DirectionalIndicatorPlus => "directionalIndicatorPlus",
            Self::DirectionalMovementIndex => "directionalMovementIndex",
            Self::AverageDirectionalMovementIndex => "averageDirectionalMovementIndex",
            Self::AverageDirectionalMovementIndexRating => "averageDirectionalMovementIndexRating",
            Self::WilliamsPercentR => "williamsPercentR",
            Self::PercentagePriceOscillator => "percentagePriceOscillator",
            Self::AbsolutePriceOscillator => "absolutePriceOscillator",
            Self::CommodityChannelIndex => "commodityChannelIndex",
            Self::MoneyFlowIndex => "moneyFlowIndex",
            Self::OnBalanceVolume => "onBalanceVolume",
            Self::BalanceOfPower => "balanceOfPower",
            Self::RateOfChangeRatio => "rateOfChangeRatio",
            Self::PearsonsCorrelationCoefficient => "pearsonsCorrelationCoefficient",
            Self::LinearRegression => "linearRegression",
            Self::UltimateOscillator => "ultimateOscillator",
            Self::StochasticRelativeStrengthIndex => "stochasticRelativeStrengthIndex",
            Self::Stochastic => "stochastic",
            Self::Aroon => "aroon",
            Self::AdvanceDecline => "advanceDecline",
            Self::AdvanceDeclineOscillator => "advanceDeclineOscillator",
            Self::ParabolicStopAndReverse => "parabolicStopAndReverse",
            Self::TripleExponentialMovingAverageOscillator => {
                "tripleExponentialMovingAverageOscillator"
            }
            Self::BollingerBandsTrend => "bollingerBandsTrend",
            Self::MovingAverageConvergenceDivergence => "movingAverageConvergenceDivergence",
            Self::SineWave => "sineWave",
            Self::HilbertTransformerInstantaneousTrendLine => {
                "hilbertTransformerInstantaneousTrendLine"
            }
            Self::TrendCycleMode => "trendCycleMode",
            Self::CoronaSpectrum => "coronaSpectrum",
            Self::CoronaSignalToNoiseRatio => "coronaSignalToNoiseRatio",
            Self::CoronaSwingPosition => "coronaSwingPosition",
            Self::CoronaTrendVigor => "coronaTrendVigor",
            Self::AdaptiveTrendAndCycleFilter => "adaptiveTrendAndCycleFilter",
            Self::MaximumEntropySpectrum => "maximumEntropySpectrum",
            Self::DiscreteFourierTransformSpectrum => "discreteFourierTransformSpectrum",
            Self::CombBandPassSpectrum => "combBandPassSpectrum",
            Self::AutoCorrelationIndicator => "autoCorrelationIndicator",
            Self::AutoCorrelationPeriodogram => "autoCorrelationPeriodogram",
            Self::JurikRelativeTrendStrengthIndex => "jurikRelativeTrendStrengthIndex",
            Self::JurikCompositeFractalBehaviorIndex => "jurikCompositeFractalBehaviorIndex",
            Self::JurikZeroLagVelocity => "jurikZeroLagVelocity",
            Self::JurikDirectionalMovementIndex => "jurikDirectionalMovementIndex",
            Self::JurikTurningPointOscillator => "jurikTurningPointOscillator",
            Self::JurikWaveletSampler => "jurikWaveletSampler",
            Self::JurikCommodityChannelIndex => "jurikCommodityChannelIndex",
            Self::JurikAdaptiveZeroLagVelocity => "jurikAdaptiveZeroLagVelocity",
            Self::JurikFractalAdaptiveZeroLagVelocity => "jurikFractalAdaptiveZeroLagVelocity",
            Self::JurikAdaptiveRelativeTrendStrengthIndex => "jurikAdaptiveRelativeTrendStrengthIndex",
        }
    }

    /// Parses a camelCase string into an Identifier.
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "simpleMovingAverage" => Some(Self::SimpleMovingAverage),
            "weightedMovingAverage" => Some(Self::WeightedMovingAverage),
            "triangularMovingAverage" => Some(Self::TriangularMovingAverage),
            "exponentialMovingAverage" => Some(Self::ExponentialMovingAverage),
            "doubleExponentialMovingAverage" => Some(Self::DoubleExponentialMovingAverage),
            "tripleExponentialMovingAverage" => Some(Self::TripleExponentialMovingAverage),
            "t2ExponentialMovingAverage" => Some(Self::T2ExponentialMovingAverage),
            "t3ExponentialMovingAverage" => Some(Self::T3ExponentialMovingAverage),
            "kaufmanAdaptiveMovingAverage" => Some(Self::KaufmanAdaptiveMovingAverage),
            "jurikMovingAverage" => Some(Self::JurikMovingAverage),
            "mesaAdaptiveMovingAverage" => Some(Self::MesaAdaptiveMovingAverage),
            "fractalAdaptiveMovingAverage" => Some(Self::FractalAdaptiveMovingAverage),
            "dominantCycle" => Some(Self::DominantCycle),
            "momentum" => Some(Self::Momentum),
            "rateOfChange" => Some(Self::RateOfChange),
            "rateOfChangePercent" => Some(Self::RateOfChangePercent),
            "relativeStrengthIndex" => Some(Self::RelativeStrengthIndex),
            "chandeMomentumOscillator" => Some(Self::ChandeMomentumOscillator),
            "bollingerBands" => Some(Self::BollingerBands),
            "variance" => Some(Self::Variance),
            "standardDeviation" => Some(Self::StandardDeviation),
            "goertzelSpectrum" => Some(Self::GoertzelSpectrum),
            "centerOfGravityOscillator" => Some(Self::CenterOfGravityOscillator),
            "cyberCycle" => Some(Self::CyberCycle),
            "instantaneousTrendLine" => Some(Self::InstantaneousTrendLine),
            "superSmoother" => Some(Self::SuperSmoother),
            "zeroLagExponentialMovingAverage" => Some(Self::ZeroLagExponentialMovingAverage),
            "zeroLagErrorCorrectingExponentialMovingAverage" => {
                Some(Self::ZeroLagErrorCorrectingExponentialMovingAverage)
            }
            "roofingFilter" => Some(Self::RoofingFilter),
            "trueRange" => Some(Self::TrueRange),
            "averageTrueRange" => Some(Self::AverageTrueRange),
            "normalizedAverageTrueRange" => Some(Self::NormalizedAverageTrueRange),
            "directionalMovementMinus" => Some(Self::DirectionalMovementMinus),
            "directionalMovementPlus" => Some(Self::DirectionalMovementPlus),
            "directionalIndicatorMinus" => Some(Self::DirectionalIndicatorMinus),
            "directionalIndicatorPlus" => Some(Self::DirectionalIndicatorPlus),
            "directionalMovementIndex" => Some(Self::DirectionalMovementIndex),
            "averageDirectionalMovementIndex" => Some(Self::AverageDirectionalMovementIndex),
            "averageDirectionalMovementIndexRating" => {
                Some(Self::AverageDirectionalMovementIndexRating)
            }
            "williamsPercentR" => Some(Self::WilliamsPercentR),
            "percentagePriceOscillator" => Some(Self::PercentagePriceOscillator),
            "absolutePriceOscillator" => Some(Self::AbsolutePriceOscillator),
            "commodityChannelIndex" => Some(Self::CommodityChannelIndex),
            "moneyFlowIndex" => Some(Self::MoneyFlowIndex),
            "onBalanceVolume" => Some(Self::OnBalanceVolume),
            "balanceOfPower" => Some(Self::BalanceOfPower),
            "rateOfChangeRatio" => Some(Self::RateOfChangeRatio),
            "pearsonsCorrelationCoefficient" => Some(Self::PearsonsCorrelationCoefficient),
            "linearRegression" => Some(Self::LinearRegression),
            "ultimateOscillator" => Some(Self::UltimateOscillator),
            "stochasticRelativeStrengthIndex" => Some(Self::StochasticRelativeStrengthIndex),
            "stochastic" => Some(Self::Stochastic),
            "aroon" => Some(Self::Aroon),
            "advanceDecline" => Some(Self::AdvanceDecline),
            "advanceDeclineOscillator" => Some(Self::AdvanceDeclineOscillator),
            "parabolicStopAndReverse" => Some(Self::ParabolicStopAndReverse),
            "tripleExponentialMovingAverageOscillator" => {
                Some(Self::TripleExponentialMovingAverageOscillator)
            }
            "bollingerBandsTrend" => Some(Self::BollingerBandsTrend),
            "movingAverageConvergenceDivergence" => Some(Self::MovingAverageConvergenceDivergence),
            "sineWave" => Some(Self::SineWave),
            "hilbertTransformerInstantaneousTrendLine" => {
                Some(Self::HilbertTransformerInstantaneousTrendLine)
            }
            "trendCycleMode" => Some(Self::TrendCycleMode),
            "coronaSpectrum" => Some(Self::CoronaSpectrum),
            "coronaSignalToNoiseRatio" => Some(Self::CoronaSignalToNoiseRatio),
            "coronaSwingPosition" => Some(Self::CoronaSwingPosition),
            "coronaTrendVigor" => Some(Self::CoronaTrendVigor),
            "adaptiveTrendAndCycleFilter" => Some(Self::AdaptiveTrendAndCycleFilter),
            "maximumEntropySpectrum" => Some(Self::MaximumEntropySpectrum),
            "discreteFourierTransformSpectrum" => Some(Self::DiscreteFourierTransformSpectrum),
            "combBandPassSpectrum" => Some(Self::CombBandPassSpectrum),
            "autoCorrelationIndicator" => Some(Self::AutoCorrelationIndicator),
            "autoCorrelationPeriodogram" => Some(Self::AutoCorrelationPeriodogram),
            "jurikRelativeTrendStrengthIndex" => Some(Self::JurikRelativeTrendStrengthIndex),
            "jurikCompositeFractalBehaviorIndex" => Some(Self::JurikCompositeFractalBehaviorIndex),
            "jurikZeroLagVelocity" => Some(Self::JurikZeroLagVelocity),
            "jurikDirectionalMovementIndex" => Some(Self::JurikDirectionalMovementIndex),
            "jurikTurningPointOscillator" => Some(Self::JurikTurningPointOscillator),
            "jurikWaveletSampler" => Some(Self::JurikWaveletSampler),
            "jurikCommodityChannelIndex" => Some(Self::JurikCommodityChannelIndex),
            "jurikAdaptiveZeroLagVelocity" => Some(Self::JurikAdaptiveZeroLagVelocity),
            "jurikFractalAdaptiveZeroLagVelocity" => Some(Self::JurikFractalAdaptiveZeroLagVelocity),
            "jurikAdaptiveRelativeTrendStrengthIndex" => Some(Self::JurikAdaptiveRelativeTrendStrengthIndex),
            _ => None,
        }
    }
}

impl std::fmt::Display for Identifier {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}
