// ---------------------------------------------------------------------------
// Enumeration of the 61 candlestick pattern identifiers.
// ---------------------------------------------------------------------------

/// Identifies each of the 61 candlestick patterns.
/// Values are sequential starting at 0, sorted alphabetically.
/// The field name matches the method name on CandlestickPatterns.
pub const PatternIdentifier = enum(u8) {
    abandoned_baby = 0,
    advance_block = 1,
    belt_hold = 2,
    breakaway = 3,
    closing_marubozu = 4,
    concealing_baby_swallow = 5,
    counterattack = 6,
    dark_cloud_cover = 7,
    doji = 8,
    doji_star = 9,
    dragonfly_doji = 10,
    engulfing = 11,
    evening_doji_star = 12,
    evening_star = 13,
    gravestone_doji = 14,
    hammer = 15,
    hanging_man = 16,
    harami = 17,
    harami_cross = 18,
    high_wave = 19,
    hikkake = 20,
    hikkake_modified = 21,
    homing_pigeon = 22,
    identical_three_crows = 23,
    in_neck = 24,
    inverted_hammer = 25,
    kicking = 26,
    kicking_by_length = 27,
    ladder_bottom = 28,
    long_legged_doji = 29,
    long_line = 30,
    marubozu = 31,
    matching_low = 32,
    mat_hold = 33,
    morning_doji_star = 34,
    morning_star = 35,
    on_neck = 36,
    piercing = 37,
    rickshaw_man = 38,
    rising_falling_three_methods = 39,
    separating_lines = 40,
    shooting_star = 41,
    short_line = 42,
    spinning_top = 43,
    stalled = 44,
    stick_sandwich = 45,
    takuri = 46,
    tasuki_gap = 47,
    three_black_crows = 48,
    three_inside = 49,
    three_line_strike = 50,
    three_outside = 51,
    three_stars_in_the_south = 52,
    three_white_soldiers = 53,
    thrusting = 54,
    tristar = 55,
    two_crows = 56,
    unique_three_river = 57,
    up_down_gap_side_by_side_white_lines = 58,
    upside_gap_two_crows = 59,
    x_side_gap_three_methods = 60,
};

/// Total number of patterns.
pub const pattern_count: usize = 61;
