/// Identifies an indicator by enumerating all implemented indicators.
/// Values are 0-based.
pub const Identifier = enum(u8) {
    simple_moving_average = 0,
    weighted_moving_average = 1,
    triangular_moving_average = 2,
    exponential_moving_average = 3,
    double_exponential_moving_average = 4,
    triple_exponential_moving_average = 5,
    t2_exponential_moving_average = 6,
    t3_exponential_moving_average = 7,
    kaufman_adaptive_moving_average = 8,
    jurik_moving_average = 9,
    mesa_adaptive_moving_average = 10,
    fractal_adaptive_moving_average = 11,
    dominant_cycle = 12,
    momentum = 13,
    rate_of_change = 14,
    rate_of_change_percent = 15,
    relative_strength_index = 16,
    chande_momentum_oscillator = 17,
    bollinger_bands = 18,
    variance = 19,
    standard_deviation = 20,
    goertzel_spectrum = 21,
    center_of_gravity_oscillator = 22,
    cyber_cycle = 23,
    instantaneous_trend_line = 24,
    super_smoother = 25,
    zero_lag_exponential_moving_average = 26,
    zero_lag_error_correcting_exponential_moving_average = 27,
    roofing_filter = 28,
    true_range = 29,
    average_true_range = 30,
    normalized_average_true_range = 31,
    directional_movement_minus = 32,
    directional_movement_plus = 33,
    directional_indicator_minus = 34,
    directional_indicator_plus = 35,
    directional_movement_index = 36,
    average_directional_movement_index = 37,
    average_directional_movement_index_rating = 38,
    williams_percent_r = 39,
    percentage_price_oscillator = 40,
    absolute_price_oscillator = 41,
    commodity_channel_index = 42,
    money_flow_index = 43,
    on_balance_volume = 44,
    balance_of_power = 45,
    rate_of_change_ratio = 46,
    pearsons_correlation_coefficient = 47,
    linear_regression = 48,
    ultimate_oscillator = 49,
    stochastic_relative_strength_index = 50,
    stochastic = 51,
    aroon = 52,
    advance_decline = 53,
    advance_decline_oscillator = 54,
    parabolic_stop_and_reverse = 55,
    triple_exponential_moving_average_oscillator = 56,
    bollinger_bands_trend = 57,
    moving_average_convergence_divergence = 58,
    sine_wave = 59,
    hilbert_transformer_instantaneous_trend_line = 60,
    trend_cycle_mode = 61,
    corona_spectrum = 62,
    corona_signal_to_noise_ratio = 63,
    corona_swing_position = 64,
    corona_trend_vigor = 65,
    adaptive_trend_and_cycle_filter = 66,
    maximum_entropy_spectrum = 67,
    discrete_fourier_transform_spectrum = 68,
    comb_band_pass_spectrum = 69,
    auto_correlation_indicator = 70,
    auto_correlation_periodogram = 71,
    jurik_relative_trend_strength_index = 72,
    jurik_composite_fractal_behavior_index = 73,
    jurik_zero_lag_velocity = 74,
    jurik_directional_movement_index = 75,
    jurik_commodity_channel_index = 76,
    jurik_wavelet_sampler = 77,
    jurik_adaptive_zero_lag_velocity = 78,
    jurik_fractal_adaptive_zero_lag_velocity = 79,
    jurik_adaptive_relative_trend_strength_index = 80,
    jurik_turning_point_oscillator = 81,
    arnaud_legoux_moving_average = 82,

    /// Returns the camelCase string representation matching Go's String().
    pub fn asStr(self: Identifier) []const u8 {
        return switch (self) {
            .simple_moving_average => "simpleMovingAverage",
            .weighted_moving_average => "weightedMovingAverage",
            .triangular_moving_average => "triangularMovingAverage",
            .exponential_moving_average => "exponentialMovingAverage",
            .double_exponential_moving_average => "doubleExponentialMovingAverage",
            .triple_exponential_moving_average => "tripleExponentialMovingAverage",
            .t2_exponential_moving_average => "t2ExponentialMovingAverage",
            .t3_exponential_moving_average => "t3ExponentialMovingAverage",
            .kaufman_adaptive_moving_average => "kaufmanAdaptiveMovingAverage",
            .jurik_moving_average => "jurikMovingAverage",
            .mesa_adaptive_moving_average => "mesaAdaptiveMovingAverage",
            .fractal_adaptive_moving_average => "fractalAdaptiveMovingAverage",
            .dominant_cycle => "dominantCycle",
            .momentum => "momentum",
            .rate_of_change => "rateOfChange",
            .rate_of_change_percent => "rateOfChangePercent",
            .relative_strength_index => "relativeStrengthIndex",
            .chande_momentum_oscillator => "chandeMomentumOscillator",
            .bollinger_bands => "bollingerBands",
            .variance => "variance",
            .standard_deviation => "standardDeviation",
            .goertzel_spectrum => "goertzelSpectrum",
            .center_of_gravity_oscillator => "centerOfGravityOscillator",
            .cyber_cycle => "cyberCycle",
            .instantaneous_trend_line => "instantaneousTrendLine",
            .super_smoother => "superSmoother",
            .zero_lag_exponential_moving_average => "zeroLagExponentialMovingAverage",
            .zero_lag_error_correcting_exponential_moving_average => "zeroLagErrorCorrectingExponentialMovingAverage",
            .roofing_filter => "roofingFilter",
            .true_range => "trueRange",
            .average_true_range => "averageTrueRange",
            .normalized_average_true_range => "normalizedAverageTrueRange",
            .directional_movement_minus => "directionalMovementMinus",
            .directional_movement_plus => "directionalMovementPlus",
            .directional_indicator_minus => "directionalIndicatorMinus",
            .directional_indicator_plus => "directionalIndicatorPlus",
            .directional_movement_index => "directionalMovementIndex",
            .average_directional_movement_index => "averageDirectionalMovementIndex",
            .average_directional_movement_index_rating => "averageDirectionalMovementIndexRating",
            .williams_percent_r => "williamsPercentR",
            .percentage_price_oscillator => "percentagePriceOscillator",
            .absolute_price_oscillator => "absolutePriceOscillator",
            .commodity_channel_index => "commodityChannelIndex",
            .money_flow_index => "moneyFlowIndex",
            .on_balance_volume => "onBalanceVolume",
            .balance_of_power => "balanceOfPower",
            .rate_of_change_ratio => "rateOfChangeRatio",
            .pearsons_correlation_coefficient => "pearsonsCorrelationCoefficient",
            .linear_regression => "linearRegression",
            .ultimate_oscillator => "ultimateOscillator",
            .stochastic_relative_strength_index => "stochasticRelativeStrengthIndex",
            .stochastic => "stochastic",
            .aroon => "aroon",
            .advance_decline => "advanceDecline",
            .advance_decline_oscillator => "advanceDeclineOscillator",
            .parabolic_stop_and_reverse => "parabolicStopAndReverse",
            .triple_exponential_moving_average_oscillator => "tripleExponentialMovingAverageOscillator",
            .bollinger_bands_trend => "bollingerBandsTrend",
            .moving_average_convergence_divergence => "movingAverageConvergenceDivergence",
            .sine_wave => "sineWave",
            .hilbert_transformer_instantaneous_trend_line => "hilbertTransformerInstantaneousTrendLine",
            .trend_cycle_mode => "trendCycleMode",
            .corona_spectrum => "coronaSpectrum",
            .corona_signal_to_noise_ratio => "coronaSignalToNoiseRatio",
            .corona_swing_position => "coronaSwingPosition",
            .corona_trend_vigor => "coronaTrendVigor",
            .adaptive_trend_and_cycle_filter => "adaptiveTrendAndCycleFilter",
            .maximum_entropy_spectrum => "maximumEntropySpectrum",
            .discrete_fourier_transform_spectrum => "discreteFourierTransformSpectrum",
            .comb_band_pass_spectrum => "combBandPassSpectrum",
            .auto_correlation_indicator => "autoCorrelationIndicator",
            .auto_correlation_periodogram => "autoCorrelationPeriodogram",
            .jurik_relative_trend_strength_index => "jurikRelativeTrendStrengthIndex",
            .jurik_composite_fractal_behavior_index => "jurikCompositeFractalBehaviorIndex",
            .jurik_zero_lag_velocity => "jurikZeroLagVelocity",
            .jurik_directional_movement_index => "jurikDirectionalMovementIndex",
            .jurik_commodity_channel_index => "jurikCommodityChannelIndex",
            .jurik_wavelet_sampler => "jurikWaveletSampler",
            .jurik_adaptive_zero_lag_velocity => "jurikAdaptiveZeroLagVelocity",
            .jurik_fractal_adaptive_zero_lag_velocity => "jurikFractalAdaptiveZeroLagVelocity",
            .jurik_adaptive_relative_trend_strength_index => "jurikAdaptiveRelativeTrendStrengthIndex",
            .jurik_turning_point_oscillator => "jurikTurningPointOscillator",
            .arnaud_legoux_moving_average => "arnaudLegouxMovingAverage",
        };
    }

    /// Parses a camelCase string into an Identifier.
    pub fn fromStr(s: []const u8) ?Identifier {
        const map = .{
            .{ "simpleMovingAverage", Identifier.simple_moving_average },
            .{ "weightedMovingAverage", Identifier.weighted_moving_average },
            .{ "triangularMovingAverage", Identifier.triangular_moving_average },
            .{ "exponentialMovingAverage", Identifier.exponential_moving_average },
            .{ "doubleExponentialMovingAverage", Identifier.double_exponential_moving_average },
            .{ "tripleExponentialMovingAverage", Identifier.triple_exponential_moving_average },
            .{ "t2ExponentialMovingAverage", Identifier.t2_exponential_moving_average },
            .{ "t3ExponentialMovingAverage", Identifier.t3_exponential_moving_average },
            .{ "kaufmanAdaptiveMovingAverage", Identifier.kaufman_adaptive_moving_average },
            .{ "jurikMovingAverage", Identifier.jurik_moving_average },
            .{ "mesaAdaptiveMovingAverage", Identifier.mesa_adaptive_moving_average },
            .{ "fractalAdaptiveMovingAverage", Identifier.fractal_adaptive_moving_average },
            .{ "dominantCycle", Identifier.dominant_cycle },
            .{ "momentum", Identifier.momentum },
            .{ "rateOfChange", Identifier.rate_of_change },
            .{ "rateOfChangePercent", Identifier.rate_of_change_percent },
            .{ "relativeStrengthIndex", Identifier.relative_strength_index },
            .{ "chandeMomentumOscillator", Identifier.chande_momentum_oscillator },
            .{ "bollingerBands", Identifier.bollinger_bands },
            .{ "variance", Identifier.variance },
            .{ "standardDeviation", Identifier.standard_deviation },
            .{ "goertzelSpectrum", Identifier.goertzel_spectrum },
            .{ "centerOfGravityOscillator", Identifier.center_of_gravity_oscillator },
            .{ "cyberCycle", Identifier.cyber_cycle },
            .{ "instantaneousTrendLine", Identifier.instantaneous_trend_line },
            .{ "superSmoother", Identifier.super_smoother },
            .{ "zeroLagExponentialMovingAverage", Identifier.zero_lag_exponential_moving_average },
            .{ "zeroLagErrorCorrectingExponentialMovingAverage", Identifier.zero_lag_error_correcting_exponential_moving_average },
            .{ "roofingFilter", Identifier.roofing_filter },
            .{ "trueRange", Identifier.true_range },
            .{ "averageTrueRange", Identifier.average_true_range },
            .{ "normalizedAverageTrueRange", Identifier.normalized_average_true_range },
            .{ "directionalMovementMinus", Identifier.directional_movement_minus },
            .{ "directionalMovementPlus", Identifier.directional_movement_plus },
            .{ "directionalIndicatorMinus", Identifier.directional_indicator_minus },
            .{ "directionalIndicatorPlus", Identifier.directional_indicator_plus },
            .{ "directionalMovementIndex", Identifier.directional_movement_index },
            .{ "averageDirectionalMovementIndex", Identifier.average_directional_movement_index },
            .{ "averageDirectionalMovementIndexRating", Identifier.average_directional_movement_index_rating },
            .{ "williamsPercentR", Identifier.williams_percent_r },
            .{ "percentagePriceOscillator", Identifier.percentage_price_oscillator },
            .{ "absolutePriceOscillator", Identifier.absolute_price_oscillator },
            .{ "commodityChannelIndex", Identifier.commodity_channel_index },
            .{ "moneyFlowIndex", Identifier.money_flow_index },
            .{ "onBalanceVolume", Identifier.on_balance_volume },
            .{ "balanceOfPower", Identifier.balance_of_power },
            .{ "rateOfChangeRatio", Identifier.rate_of_change_ratio },
            .{ "pearsonsCorrelationCoefficient", Identifier.pearsons_correlation_coefficient },
            .{ "linearRegression", Identifier.linear_regression },
            .{ "ultimateOscillator", Identifier.ultimate_oscillator },
            .{ "stochasticRelativeStrengthIndex", Identifier.stochastic_relative_strength_index },
            .{ "stochastic", Identifier.stochastic },
            .{ "aroon", Identifier.aroon },
            .{ "advanceDecline", Identifier.advance_decline },
            .{ "advanceDeclineOscillator", Identifier.advance_decline_oscillator },
            .{ "parabolicStopAndReverse", Identifier.parabolic_stop_and_reverse },
            .{ "tripleExponentialMovingAverageOscillator", Identifier.triple_exponential_moving_average_oscillator },
            .{ "bollingerBandsTrend", Identifier.bollinger_bands_trend },
            .{ "movingAverageConvergenceDivergence", Identifier.moving_average_convergence_divergence },
            .{ "sineWave", Identifier.sine_wave },
            .{ "hilbertTransformerInstantaneousTrendLine", Identifier.hilbert_transformer_instantaneous_trend_line },
            .{ "trendCycleMode", Identifier.trend_cycle_mode },
            .{ "coronaSpectrum", Identifier.corona_spectrum },
            .{ "coronaSignalToNoiseRatio", Identifier.corona_signal_to_noise_ratio },
            .{ "coronaSwingPosition", Identifier.corona_swing_position },
            .{ "coronaTrendVigor", Identifier.corona_trend_vigor },
            .{ "adaptiveTrendAndCycleFilter", Identifier.adaptive_trend_and_cycle_filter },
            .{ "maximumEntropySpectrum", Identifier.maximum_entropy_spectrum },
            .{ "discreteFourierTransformSpectrum", Identifier.discrete_fourier_transform_spectrum },
            .{ "combBandPassSpectrum", Identifier.comb_band_pass_spectrum },
            .{ "autoCorrelationIndicator", Identifier.auto_correlation_indicator },
            .{ "autoCorrelationPeriodogram", Identifier.auto_correlation_periodogram },
            .{ "jurikRelativeTrendStrengthIndex", Identifier.jurik_relative_trend_strength_index },
            .{ "jurikCompositeFractalBehaviorIndex", Identifier.jurik_composite_fractal_behavior_index },
            .{ "jurikZeroLagVelocity", Identifier.jurik_zero_lag_velocity },
            .{ "jurikDirectionalMovementIndex", Identifier.jurik_directional_movement_index },
            .{ "jurikCommodityChannelIndex", Identifier.jurik_commodity_channel_index },
            .{ "jurikWaveletSampler", Identifier.jurik_wavelet_sampler },
            .{ "jurikAdaptiveZeroLagVelocity", Identifier.jurik_adaptive_zero_lag_velocity },
            .{ "jurikFractalAdaptiveZeroLagVelocity", Identifier.jurik_fractal_adaptive_zero_lag_velocity },
            .{ "jurikAdaptiveRelativeTrendStrengthIndex", Identifier.jurik_adaptive_relative_trend_strength_index },
            .{ "jurikTurningPointOscillator", Identifier.jurik_turning_point_oscillator },
            .{ "arnaudLegouxMovingAverage", Identifier.arnaud_legoux_moving_average },
        };

        inline for (map) |entry| {
            if (std.mem.eql(u8, s, entry[0])) return entry[1];
        }
        return null;
    }
};

const std = @import("std");
const testing = std.testing;

test "identifier asStr round-trip" {
    // Test a few representative identifiers.
    try testing.expectEqualStrings("simpleMovingAverage", Identifier.simple_moving_average.asStr());
    try testing.expectEqualStrings("bollingerBands", Identifier.bollinger_bands.asStr());
    try testing.expectEqualStrings("autoCorrelationPeriodogram", Identifier.auto_correlation_periodogram.asStr());
}

test "identifier fromStr round-trip" {
    try testing.expectEqual(Identifier.simple_moving_average, Identifier.fromStr("simpleMovingAverage").?);
    try testing.expectEqual(Identifier.bollinger_bands, Identifier.fromStr("bollingerBands").?);
    try testing.expectEqual(@as(?Identifier, null), Identifier.fromStr("nonExistent"));
}

test "identifier fromStr all variants" {
    // Verify every variant round-trips through asStr/fromStr.
    inline for (std.meta.fields(Identifier)) |field| {
        const id: Identifier = @enumFromInt(field.value);
        const str = id.asStr();
        const parsed = Identifier.fromStr(str);
        try testing.expectEqual(id, parsed.?);
    }
}
